# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_loginscu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
